# Audio configuration
FORMAT = None  # Will be set after pyaudio import
CHANNELS = 1
RATE = 16000
CHUNK = 320  # 20ms at 16kHz (standard Opus VoIP frame size)

# Message type constants
MSG_TYPE_JOIN = 1
MSG_TYPE_AUDIO = 2
MSG_TYPE_ADMIN_JOIN = 4
MSG_TYPE_USER_LIST = 5
MSG_TYPE_USER_JOINED = 6
MSG_TYPE_HEARTBEAT = 7
MSG_TYPE_LEAVE = 8
MSG_TYPE_AUTH_SUCCESS = 9
MSG_TYPE_AUTH_FAIL = 10
MSG_TYPE_ADMIN_BAN = 11
MSG_TYPE_ADMIN_KICK = 12
MSG_TYPE_BANNED = 13
MSG_TYPE_ADMIN_GET_BAN_LIST = 14
MSG_TYPE_BAN_LIST = 15
MSG_TYPE_ADMIN_UNBAN = 16
MSG_TYPE_ADMIN_NOT_ONLINE = 17
MSG_TYPE_RECORDING_NOTICE = 18
MSG_TYPE_RECORDING_CONSENT = 19
MSG_TYPE_UDP_PORT = 20
MSG_TYPE_ADMIN_ONLINE = 21
MSG_TYPE_ADMIN_OFFLINE = 22
MSG_TYPE_DUPLICATE_NAME = 23
MSG_TYPE_TEXT_CHAT = 24
MSG_TYPE_TEXT_MESSAGE = 25

JITTER_BUFFER_SIZE = 96  # 96 * 20ms = 1.92s buffer (min_fill = 24 frames = 480ms)
MAX_PACKET_SIZE = 65536
UDP_AUDIO_PORT = 9092


def init_audio_format(pyaudio_module):
    global FORMAT
    FORMAT = pyaudio_module.paInt16